#pragma once
#include <map>

namespace SeParameters {
enum {
PARAM_AMNT___KEY_TRACK = 1,
PARAM_AMNT__DELAY = 2,
PARAM_DELAY = 3,
PARAM_KEY_FOLLOW = 4,
PARAM_PORTAMENTO = 5,
PARAM_RETRIGGER = 6,
PARAM_FEEDBK = 7,
PARAM_WAVE2 = 9,
PARAM_WAVE = 10,
PARAM_DECAY = 11,
PARAM_ENV_MOD = 12,
PARAM_CUTTOFF = 13,
PARAM_POLYPHONY = 622988279,
PARAM_PROGRAM_NAME = 1041141624,
PARAM_RESERVEVOICES = 1053706668,
PARAM_BENDER = 1621701472,
PARAM_HOLDPEDAL = 2026708959,
NUM_PARAMS
};


#ifdef _DEBUG
inline static std::map<int32_t, const char*> parameterNames =
{
{PARAM_AMNT___KEY_TRACK, "PARAM_AMNT___KEY_TRACK"},
{PARAM_AMNT__DELAY, "PARAM_AMNT__DELAY"},
{PARAM_DELAY, "PARAM_DELAY"},
{PARAM_KEY_FOLLOW, "PARAM_KEY_FOLLOW"},
{PARAM_PORTAMENTO, "PARAM_PORTAMENTO"},
{PARAM_RETRIGGER, "PARAM_RETRIGGER"},
{PARAM_FEEDBK, "PARAM_FEEDBK"},
{PARAM_WAVE2, "PARAM_WAVE2"},
{PARAM_WAVE, "PARAM_WAVE"},
{PARAM_DECAY, "PARAM_DECAY"},
{PARAM_ENV_MOD, "PARAM_ENV_MOD"},
{PARAM_CUTTOFF, "PARAM_CUTTOFF"},
{PARAM_POLYPHONY, "PARAM_POLYPHONY"},
{PARAM_PROGRAM_NAME, "PARAM_PROGRAM_NAME"},
{PARAM_RESERVEVOICES, "PARAM_RESERVEVOICES"},
{PARAM_BENDER, "PARAM_BENDER"},
{PARAM_HOLDPEDAL, "PARAM_HOLDPEDAL"},

};
inline const char* getParameterName(int32_t param)
{
	auto it = parameterNames.find(param);
	if (it != parameterNames.end())
		return it->second;
	return "Unknown";
}
#endif
}